# Generated by Django 6.1 on 2026-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_model',
            name='link',
            field=models.URLField(default=None),
        ),
    ]
